#!/usr/bin/env python3
"""Generate a PowerPoint-style GRIN slide menu from slides.json."""
from __future__ import annotations

import json
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "slides.json"
ASSETS = ROOT / "assets"
SHOW = ROOT / "slides-menu.txt"


def font(path: str | None, size: int, bold: bool = False):
    candidates = []
    if path:
        candidates.append(Path(path))
    candidates += [
        Path("/usr/share/fonts/TTF/DejaVuSans-Bold.ttf" if bold else "/usr/share/fonts/TTF/DejaVuSans.ttf"),
        Path("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf" if bold else "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"),
    ]
    for c in candidates:
        if c.exists():
            return ImageFont.truetype(str(c), size)
    return ImageFont.load_default()


def rounded_rect(draw, xy, radius, fill, outline=None, width=1):
    draw.rounded_rectangle(xy, radius=radius, fill=fill, outline=outline, width=width)


def text_center(draw, xy, text, fnt, fill):
    x, y, w, h = xy
    bbox = draw.textbbox((0, 0), text, font=fnt)
    tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
    draw.text((x + (w - tw) / 2, y + (h - th) / 2 - 3), text, font=fnt, fill=fill)


def render_assets(cfg):
    ASSETS.mkdir(exist_ok=True)
    width, height = cfg.get("resolution", [1920, 1080])
    theme = cfg.get("theme", {})
    title_font = font(theme.get("font"), theme.get("title_font_size", 64), True)
    body_font = font(theme.get("font"), theme.get("body_font_size", 34))
    button_font = font(theme.get("font"), theme.get("button_font_size", 34), True)

    for idx, slide in enumerate(cfg["slides"], 1):
        bg = tuple(slide.get("background", [22, 35, 55]))
        accent = tuple(slide.get("accent", [80, 160, 255]))
        im = Image.new("RGBA", (width, height), bg + (255,))
        d = ImageDraw.Draw(im)

        # Background: soft diagonal panels / presentation-card layout.
        d.polygon([(0, 0), (width * 0.72, 0), (width * 0.52, height), (0, height)], fill=tuple(min(255, c + 18) for c in bg) + (255,))
        d.rectangle((0, 0, width, int(height * 0.122)), fill=(0, 0, 0, 70))
        d.rectangle((0, int(height * 0.122), width, int(height * 0.132)), fill=accent + (255,))
        d.ellipse((width - int(width*.245), -int(height*.194), width + int(width*.089), int(height*.398)), fill=accent + (42,))
        d.ellipse((width - int(width*.146), height - int(height*.222), width + int(width*.073), height + int(height*.167)), fill=(255, 255, 255, 28))

        d.text((int(width*.057), int(height*.035)), slide["title"], font=title_font, fill=(255, 255, 255, 255))
        d.text((int(width*.059), int(height*.156)), slide.get("subtitle", ""), font=body_font, fill=(218, 232, 255, 245))
        y = int(height*.278)
        for line in slide.get("body", []):
            d.text((int(width*.078), y), "• " + line, font=body_font, fill=(245, 248, 255, 235))
            y += int(height*.054)

        d.text((int(width*.802), int(height*.041)), f"{idx}/{len(cfg['slides'])}", font=body_font, fill=(255, 255, 255, 210))

        for btn in slide.get("buttons", []):
            x, y, w, h = btn["x"], btn["y"], btn["w"], btn["h"]
            rounded_rect(d, (x, y, x + w, y + h), 24, (255, 255, 255, 38), (255, 255, 255, 130), 3)
            text_center(d, (x, y, w, h), btn["label"], button_font, (255, 255, 255, 235))

            # selected/activated overlays are separate transparent PNGs.
            for state, fill, outline in [
                ("selected", accent + (86,), (255, 255, 255, 230)),
                ("activated", accent + (155,), (255, 255, 255, 255)),
            ]:
                # Keep overlays button-sized. Full-screen overlays make GRIN's
                # mosaic optimizer huge and can fail on legacy JVM/tooling.
                pad = 10
                ov = Image.new("RGBA", (w + pad * 2, h + pad * 2), (0, 0, 0, 0))
                od = ImageDraw.Draw(ov)
                rounded_rect(od, (2, 2, w + pad * 2 - 2, h + pad * 2 - 2), 30, fill, outline, 5)
                text_center(od, (pad, pad, w, h), btn["label"], button_font, (255, 255, 255, 255))
                ov.save(ASSETS / f"{slide['id']}_{btn['id']}_{state}.png")

        im.save(ASSETS / f"{slide['id']}_bg.png")


def ident(s):
    return "".join(ch if ch.isalnum() else "_" for ch in s)


def generate_show(cfg):
    slides = cfg["slides"]
    lines = ["# Generated by tools/generate_slides_menu.py", "show", ""]
    lines += [
        "segment S:Initialize",
        "    setup {",
        "        F:home.BG",
        "    } setup_done {",
        "        activate_segment S:home ;",
        "    }",
        ";",
        "",
    ]

    for slide in slides:
        sid = ident(slide["id"])
        lines += [
            f"segment S:{sid}",
            "    active {",
            f"        F:{sid}.BG",
            f"        F:{sid}.Buttons",
            "    } setup {",
            f"        F:{sid}.BG",
            f"        F:{sid}.Buttons",
            "    } rc_handlers {",
            f"        R:{sid}",
            "    }",
            ";",
            "",
        ]

    for slide in slides:
        sid = ident(slide["id"])
        lines.append(f'feature fixed_image F:{sid}.BG 0 0 "assets/{slide["id"]}_bg.png" ;')
        for btn in slide.get("buttons", []):
            bid = ident(btn["id"])
            x = int(btn["x"]) - 10
            y = int(btn["y"]) - 10
            lines.append(f'feature fixed_image F:{sid}.{bid}.Selected {x} {y} "assets/{slide["id"]}_{btn["id"]}_selected.png" ;')
            lines.append(f'feature fixed_image F:{sid}.{bid}.Activated {x} {y} "assets/{slide["id"]}_{btn["id"]}_activated.png" ;')
        lines.append("")

    for slide in slides:
        sid = ident(slide["id"])
        buttons = slide.get("buttons", [])
        lines += [
            f"feature assembly F:{sid}.Buttons {{",
        ]
        for btn in buttons:
            bid = ident(btn["id"])
            lines.append(f"    {bid}_selected       F:{sid}.{bid}.Selected")
            lines.append(f"    {bid}_activated      F:{sid}.{bid}.Activated")
        lines += ["} ;", ""]

        grid = " ".join(ident(b["id"]) for b in buttons) or "home"
        lines += [
            f"rc_handler visual R:{sid}",
            f"    grid {{ {{ {grid} }} }}",
            f"    assembly F:{sid}.Buttons",
            "        start_selected true",
            "    select {",
        ]
        for btn in buttons:
            bid = ident(btn["id"])
            lines.append(f"        {bid}        {bid}_selected")
        lines.append("    }")
        lines.append("    activate {")
        for btn in buttons:
            bid = ident(btn["id"])
            target = ident(btn.get("target", slide["id"]))
            lines.append(f"        {bid}        {bid}_activated {{ activate_segment S:{target} ; }}")
        lines.append("    }")
        lines.append("    mouse {")
        for btn in buttons:
            bid = ident(btn["id"])
            x, y, w, h = btn["x"], btn["y"], btn["w"], btn["h"]
            lines.append(f"        {bid}        ( {x} {y} {x+w} {y+h} )")
        lines += ["    }", ";", ""]

    lines.append("end_show")
    SHOW.write_text("\n".join(lines) + "\n")


def main():
    cfg = json.loads(CONFIG.read_text())
    render_assets(cfg)
    generate_show(cfg)
    print(f"Generated {SHOW.relative_to(ROOT)} and {len(list(ASSETS.glob('*.png')))} PNG assets")


if __name__ == "__main__":
    main()
