#!/usr/bin/env bash
set -euo pipefail
PROJECT_DIR="${1:-/home/corey/.openclaw/Bluray project}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
if [[ ! -f "$ROOT/user.vars.properties" ]]; then
  cat > "$ROOT/user.vars.properties" <<EOF
# Generated by scripts/convert-pptx-menu.sh.
# Local override; not committed.
HDC_BDJ_PLATFORM_CLASSES=$ROOT/lib/stubs/enhanced/classes.zip
EOF
fi
OUT="$ROOT/xlets/grin_samples/Scripts/PptxMenu"
python3 "$ROOT/tools/pptx_menu_converter.py" "$PROJECT_DIR" "$OUT"
